import 'package:expenditure_management/models/expenditure_model.dart';

List<CategoryModel> categoryList = [
  CategoryModel(id: 1, name: "Eat and Drink", nameVn: "Ăn uống"),
  CategoryModel(id: 2, name: "Shopping", nameVn: "Mua sắm"),
  CategoryModel(id: 3, name: "Travel", nameVn: "Du lịch"),
  CategoryModel(id: 4, name: "Entertainment", nameVn: "Sự giải trí"),
  CategoryModel(id: 5, name: "Education", nameVn: "Giáo dục"),
  CategoryModel(id: 6, name: "Beauty", nameVn: "Sắc đẹp"),
  CategoryModel(id: 7, name: "Car", nameVn: "Xe hơi"),
  CategoryModel(id: 8, name: "Alcohol", nameVn: "Rượu"),
  CategoryModel(id: 9, name: "Cigarette", nameVn: "Thuốc lá"),
  CategoryModel(id: 10, name: "Electronic device", nameVn: "Thiết bị điện tử"),
  CategoryModel(id: 11, name: "Health", nameVn: "Sức khỏe"),
  CategoryModel(id: 12, name: "Repair", nameVn: "Sửa"),
  CategoryModel(id: 13, name: "House", nameVn: "Căn nhà"),
  CategoryModel(id: 14, name: "Present", nameVn: "Quà tặng"),
  CategoryModel(id: 15, name: "Donations", nameVn: "Quyên góp"),
  CategoryModel(id: 16, name: "Lottery", nameVn: "Vé số"),
  CategoryModel(id: 17, name: "Children", nameVn: "Trẻ em"),
  CategoryModel(id: 18, name: "Loan", nameVn: "Cho vay"),
  CategoryModel(id: 19, name: "Receive Salary", nameVn: "Lãnh lương"),
  CategoryModel(id: 20, name: "Bonus", nameVn: "Thưởng"),
  CategoryModel(id: 21, name: "Clothes", nameVn: "Quần áo"),
];
