// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDoHddG08AScsbZs05o-yqGcR7NS-1Hws',
    appId: '1:16505425247:web:a123e8a4374d8c8bd9faea',
    messagingSenderId: '16505425247',
    projectId: 'expenditure-management-f3ec0',
    authDomain: 'expenditure-management-f3ec0.firebaseapp.com',
    storageBucket: 'expenditure-management-f3ec0.appspot.com',
    measurementId: 'G-LVRFPYS04E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkJETcDOyN48kpSFGaf53oYlhErRjaukU',
    appId: '1:16505425247:android:8c812a60ca547a13d9faea',
    messagingSenderId: '16505425247',
    projectId: 'expenditure-management-f3ec0',
    storageBucket: 'expenditure-management-f3ec0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoFmyS6XD2XwpsaxZiaNrfnmFyK-f5QDM',
    appId: '1:16505425247:ios:581ce61212325962d9faea',
    messagingSenderId: '16505425247',
    projectId: 'expenditure-management-f3ec0',
    storageBucket: 'expenditure-management-f3ec0.appspot.com',
    iosClientId: '16505425247-76ur5lk628gfkr22je5oj1pt8kcsfs2t.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenditureManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoFmyS6XD2XwpsaxZiaNrfnmFyK-f5QDM',
    appId: '1:16505425247:ios:581ce61212325962d9faea',
    messagingSenderId: '16505425247',
    projectId: 'expenditure-management-f3ec0',
    storageBucket: 'expenditure-management-f3ec0.appspot.com',
    iosClientId: '16505425247-76ur5lk628gfkr22je5oj1pt8kcsfs2t.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenditureManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDoHddG08AScsbZs05o-yqGcR7NS-1Hws',
    appId: '1:16505425247:web:d2395061bc301c9dd9faea',
    messagingSenderId: '16505425247',
    projectId: 'expenditure-management-f3ec0',
    authDomain: 'expenditure-management-f3ec0.firebaseapp.com',
    storageBucket: 'expenditure-management-f3ec0.appspot.com',
    measurementId: 'G-T4QYEZBVHC',
  );
}
